### ISSUE TITLE
ColorMode - will stop working in Home Assistant Core 2025.3

### ISSUE THREAD

**Issue by Zappo-II** [andreasnuesslein/hass_teleco_daisy#12]
None (<class 'custom_components.teleco_daisy.light.TelecoDaisyLight'>) sets invalid supported color modes {<ColorMode.RGB: 'rgb'>, <ColorMode.BRIGHTNESS: 'brightness'>}, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/andreasnuesslein/hass_teleco_daisy/issues

**Comment by Zappo-II** [comment]
That line in my first comment is exactly the Line that HomeAssistant writes into its Logfiles...
Sorry for not marking it as code or quote...

The Homeassistant Logfile states:

```
None (<class 'custom_components.teleco_daisy.light.TelecoDaisyLight'>) sets invalid supported color modes {<ColorMode.RGB: 'rgb'>, <ColorMode.BRIGHTNESS: 'brightness'>}, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/andreasnuesslein/hass_teleco_daisy/issues
```

Just to state the obvious:

- ColorMode.RGB
- ColorMode.BRIGHTNESS

...will stop working in Home Assistant Core 2025.3

Since Your Integration tries to set those, Home Assistant proposes that I should contact You about this by opening a bug report, which I did and you obviously just closed...

**Comment by andreasnuesslein** [comment]
haha okay ^^
well, like i said in the other ticket, to avoid confusion maybe be a bit more verbose in your tickets please ;) 

(a `hi there` is a nice start)
